GITHUB_TOKEN = "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"
REPO_OWNER = "ravkambo"
REPO_NAME = "marioparty"
FILE_PATH = "games.json"
BRANCH = "main"
